ARG version
FROM almalinux:${version:-8}
#RUN /cat/etc/*release
ARG course=devops
ARG student=sivakumar
ARG duration=100hrs
ENV duration=${duration}
RUN echo "course is" ${course}, "student is"${student}, "duration is" {duration}
CMD [ "sleep","100" ]
